### ISSUE TITLE
자바스크립트 이해하기

### ISSUE THREAD

**Issue by mu-hun** [BetaF1sh/jejunu#2]
## 읽었거나 읽는 중인 책 목록

- [x] You Don't Know JS : 타입과 문법, 스코프와 클로저
- [ ] [함수형 자바스크립트 프로그래밍 - 유인동](http://www.insightbook.co.kr/12318)
- [ ] [인사이트 자바스크립트 - 송형주, 고현준](http://www.hanbit.co.kr/store/books/look.php?p_code=B6479856408)

**Comment by BetaF1sh** [comment]
'자기계발'이라는 단어가 이슈 내용에 비해 포괄적인 것 같아 수정함.

문제 해결 서적은 추후 알고리즘 이슈로 옮기자.

**Comment by BetaF1sh** [comment]
## 책 추가

- [ ] [인사이트 자바스크립트 - 송형주 , 고현준](http://www.hanbit.co.kr/store/books/look.php?p_code=B6479856408)

예전에 프로토타입 체이닝 부분까지만 읽었었음. 함수형 개념까지 이해해보자.
